src/main/java/com/cft/contacts/entities/BaseEntity.java
package com.cft.contacts.entities;

import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.MappedSuperclass;
import javax.persistence.Version;

@MappedSuperclass
public abstract class BaseEntity {

	@Id
	@GeneratedValue
	private Long id;

	@Version
	private Long version;

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Long getVersion() {
		return version;
	}

	public void setVersion(Long version) {
		this.version = version;
	}

}

src/main/java/com/cft/contacts/entities/Contact.java
package com.cft.contacts.entities;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;

import org.hibernate.validator.constraints.NotBlank;

@Entity
@Inheritance(strategy=InheritanceType.JOINED)
public abstract class Contact extends UrlEntity {

	@Column(nullable = false)
	@NotBlank
	private String surname;

	public Contact() {
	}

	public Contact(String surname) {
		this.surname = surname;
	}

	public String getSurname() {
		return surname;
	}

	public void setSurname(String name) {
		this.surname = surname;
	}

}

src/main/java/com/cft/contacts/entities/Person.java
package com.cft.contacts.entities;

import javax.persistence.Entity;

@Entity
public class Person extends Contact {

	String name;
	String surname;
	String middle;

	public Person() {
	}

	public Person(String name, String surname, String middle) {
		super(surname);
		this.name = name;
		this.surname = surname;
		this.middle = middle;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getSurname() {
		return surname;
	}

	public void setSurname(String surname) {
		this.surname = surname;
	}

	public String getMiddle() {
		return middle;
	}

	public void setMiddle(String middle) {
		this.middle = middle;
	}

}

src/main/java/com/cft/contacts/entities/UrlEntity.java
package com.cft.contacts.entities;

import javax.persistence.MappedSuperclass;

@MappedSuperclass
public class UrlEntity extends BaseEntity {

	public String getUrl() {
		return getClass().getSimpleName().toLowerCase() + "?id=" + getId();
	}

}

src/main/java/com/cft/contacts/controllers/BaseController.java
package com.cft.contacts.controllers;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.ResponseBody;


@Controller
public class BaseController {

	@RequestMapping(value = "/", method = RequestMethod.GET)
	public String getContactList() {
		return "base/index";
	}
}

src/main/java/com/cft/contacts/controllers/ContactController.java
package com.cft.contacts.controllers;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.ResponseBody;

import com.cft.contacts.entities.Contact;
import com.cft.contacts.repositories.ContactRepository;

@Controller
public class ContactController {

	@Autowired
	private ContactRepository contactRepository;

	@RequestMapping(value = "/contacts", method = RequestMethod.GET)
	public String getContactList(Model model) {
		model.addAttribute("contacts", contactRepository.findAll());
		return "contact/list";
	}

	@RequestMapping(value = "/contacts", method = RequestMethod.GET, produces = "application/json")
	public @ResponseBody List<Contact> getContactList() {
		return contactRepository.findAll();
	}

}

src/main/java/com/cft/contacts/controllers/PersonController.java
package com.cft.contacts.controllers;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

import com.cft.contacts.entities.Person;
import com.cft.contacts.repositories.PersonRepository;
import com.cft.contacts.representations.PersonRepresentation;

@Controller
public class PersonController {

	@Autowired
	private PersonRepository personRepository;

	@RequestMapping(value = "/person", params = "add", method = RequestMethod.GET)
	public String getAddPerson() {
		return "person/add";
	}

	@RequestMapping(value = "/person", params = "edit", method = RequestMethod.GET)
	public String getEditPerson(@RequestParam long id, Model model) {
		model.addAttribute("person", personRepository.findOne(id));
		return "person/edit";
	}

	@RequestMapping(value = "/person", method = RequestMethod.GET)
	public String getViewPerson(@RequestParam long id, Model model) {
		model.addAttribute("person", personRepository.findOne(id));
		return "person/view";
	}

	@RequestMapping(value = "/person/{id}", method = RequestMethod.GET, produces = "application/json")
	public @ResponseBody PersonRepresentation getPerson(@PathVariable long id) {
		return new PersonRepresentation(personRepository.findOne(id));
	}

	@RequestMapping(value = "/person", params = "add", method = RequestMethod.POST)
	public String postAddPerson(@RequestParam String name,
			@RequestParam String surname, @RequestParam String middle) {
		Person person = new Person(name, surname, middle);
		person = personRepository.save(person);

		return "redirect:person?id=" + person.getId();
	}

	@RequestMapping(value = "/person", params = "edit", method = RequestMethod.POST)
	// @Transactional
	public String postEditPerson(@RequestParam long id,
			@RequestParam String name, @RequestParam String surname,
			@RequestParam String middle) {
		personRepository.delete(id);
		Person person = new Person(name, surname, middle);
		person = personRepository.save(person);

		return "redirect:person?id=" + person.getId();
	}

	@RequestMapping(value = "/person", params = "delete", method = RequestMethod.POST)
	public String postDeletePerson(@RequestParam long id) {
		personRepository.delete(id);
		return "redirect:contacts";
	}

}

src/main/webapp/view/base/index.jsp
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<html>
<head>
<title>Добро пожаловать</title>
</head>
<body>
	<h1>Задание -> Реализовать список клиентов</h1>
	<ul>
		<li>Java Servlet -> OK</li>
		<li>Hibernate -> OK</li>
		<li>Database -> HSQLDB</li>
		<li>Минимальная информация о клиенте -> ФИО</li>
	</ul>
	<a href="contacts"> >>Перейти к простмотру задания<< </a></a>
</body>
</html>

src/main/webapp/view/contact/list.jsp
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<html>
<head>
<title>Список клиентов</title>
</head>
<body>
	<h1>Список клиентов</h1>
	<ul>
		<c:forEach var="contact" items="${contacts}">
			<li><a href="${contact.url}">${contact.name}</a></li>
		</c:forEach>
	</ul>
	<a href="person?add">Добавить клиента</a></a>
</body>
</html>

src/main/webapp/view/person/add.jsp
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<html>
<head>
<title>Добавление клиента</title>
</head>
<body>
	<h1>Добавление клиента</h1>
	<form action="person" method="post">
	<input type="hidden" name="add">
	<ul>
		<li>Имя: <input type="text" name="name"></li>
		<li>Фамилия: <input type="text" name="surname"></li>
		<li>Отчество: <input type="text" name="middle"></li>
	</ul>
	<input type="submit" value="Добавить">
	</form>
	<a href="contacts"> <<Вернуться к списку</a>
</body>
</html>

src/main/webapp/view/person/edit.jsp
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<html>
<head>
<title>Редактирование</title>
</head>
<body>
	<h1>Редактирование информации о клиенте</h1>
	<form action="person" method="post">
	<input type="hidden" name="edit">
	<input type="hidden" name="id" value="${person.id}">
	<ul>
		<li>Имя: <input type="text" name="name" value="${person.name}"></li>
		<li>Фамилия: <input type="text" name="surname" value="${person.surname}"></li>
		<li>Отчество: <input type="text" name="middle" value="${person.middle}"></li>
	</ul>
	<input type="submit" value="Редактировать">
	</form>
	<form action="person" method="post">
	<input type="hidden" name="delete">
	<input type="hidden" name="id" value="${person.id}">
	<input type="submit" value="Удалить">
	</form>
	<a href="contacts"> <<Вернуться к списку</a>
</body>
</html>

src/main/webapp/view/person/view.jsp
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<html>
<head>
<title>Клиент</title>
</head>
<body>
	<h1>Клиент</h1>
	<ul>
		<li>Имя: ${person.surname}</li>
		<li>Фамилия: ${person.name}</li>
		<li>Отчество: ${person.middle}</li>
	</ul>
	<a href="${person.url}&edit">Редактировать</a> |
	<a href="contacts"> <<Вернуться к списку</a>
</body>
</html>